env:
  global:
  - LIBRDKAFKA_VERSION=v1.9.0-RC2
  - secure: Oo6C8dY72hBKzAF6O+Zcbv8OX62hkcAUsPYRkUskMJU9LKJAe/5pDVm4K1+HZnE+7da1wqR78yaFGZ3uoH0vLXe3neNPnICdPL0wBeytfO3BLBl+jxGDjGKB16xJdPHV+K1Xn75Ao4L0+26SJhdCGOh45tN5BlVBDWmwsInRlpy84tdaLvuzhCk5N39rSxl3KvURoZmipTpFevzmtBvunqiCdnWcrHFsFv++ExRkg0sWqSm/ayBbzcIs18p+98u75rhmZgazIyKkosjfhtgWIXWb52oLf5WpuKghjzbRPa2LQSrakpCA+xvYqX12LQ2M5fJjXna9sv2Rslhv3mFyi8PqQfsqk1tW13cd+Hz7ryD9tanaBqEDv31RBa3feHcbNrZHXPtramdOczBNZy9HnywxH6F8A08Hzf278s4O8mu3/nOBJMABtcIJ3aZjECFehZO/8apbESNgNH5CLPePfhvNecI2BBi8CHKk4QRDojpIDM7diAhjO0FJiz62dCOca+0M1FVnPz66zILETTSqkDid17RSytjLnRU3gSc7hrWDrXzHk6xIWnJmTRg9SGGFCWp6DvC38LhJ2hcjrGIgHdNA2YvQApIWdEU52t8FONTTl/MMR3mP91O1oz8zktII4KABgrbmqUNH7MuwZZBOuNrXLbcYd8d8qvMakrmHUYA=
jobs:
  include:
  - name: Source package verification with Python 2.7 (Linux)
    if: false
    os: linux
    language: python
    dist: xenial
    python: '2.7'
    env: LD_LIBRARY_PATH="$PWD/tmp-build/lib"
    services: docker
  - name: Source package verification with Python 3.6 (Linux)
    if: false
    os: linux
    language: python
    dist: xenial
    python: '3.6'
    env: LD_LIBRARY_PATH="$PWD/tmp-build/lib"
    services: docker
  - name: Source package verification with Python 2.7 (OSX)
    if: false
    os: osx
    python: '2.7'
    env: DYLD_LIBRARY_PATH="$PWD/tmp-build/lib" INTERPRETER_VERSION="2.7.17"
  - name: Source package verification with Python 3.6 (OSX) +docs
    if: false
    os: osx
    python: '3.6'
    env: DYLD_LIBRARY_PATH="$PWD/tmp-build/lib" MK_DOCS="y" INTERPRETER_VERSION="3.6.5"
  - name: 'Wheels: Windows x64'
    if: tag is present
    os: windows
    language: shell
    env: BUILD_WHEELS=1
    before_install:
    - choco install python --version 3.8.0
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - ln -s /c/Python38/python.exe /c/Python38/python3.exe
    install:
    - bash tools/wheels/install-librdkafka.sh ${LIBRDKAFKA_VERSION#v} dest
    script:
    - tools/wheels/build-wheels.bat x64 win_amd64 dest wheelhouse
  - name: 'Wheels: Windows x86'
    if: tag is present
    os: windows
    language: shell
    env: BUILD_WHEELS=1
    before_install:
    - choco install python --version 3.8.0
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - ln -s /c/Python38/python.exe /c/Python38/python3.exe
    install:
    - bash tools/wheels/install-librdkafka.sh ${LIBRDKAFKA_VERSION#v} dest
    script:
    - tools/wheels/build-wheels.bat x86 win32 dest wheelhouse
  - name: 'Wheels: Linux x64'
    language: python
    python: '3.8'
    services: docker
    env: BUILD_WHEELS=1
    script:
    - mkdir wheelhouse
    - echo test > wheelhouse/test1
    - echo the testenv is ${TESTENV} .. | grep testenv

  - name: 'Wheels: MacOSX x64'
    if: tag is present
    os: osx
    language: shell
    env: BUILD_WHEELS=1
    script: tools/wheels/build-wheels.sh ${LIBRDKAFKA_VERSION#v} wheelhouse
deploy:
  provider: s3
#  edge: true
  access_key_id:
    secure: BMrIjoMbcTad50/A6WcG+uIuNmvva72KVu+gUs85ZhGQ+7u645XsfrZGCSHA+suP8iD7vIaiw97PgGHN2b0Wg9quB65Zqw8vbJ+dGoYBc+O1fjwC9RL6i4BPe6wPqYy/TVVwC11A8Iw75emRlHDmMVf9Z0FRWp83rB+JBT599O7dEl57lv3i6rxjiNAGVIUeY0oQAdhBhWne2TNIHfMsyFHoJ9QV+s1gAK/oe71JPErABTow2oKgfbzK9GOHKk/A77oFDejy3TQr2TbOMAyZJEVzDl8aoZO2dem6fR+wjOQA127gpMIfU74oOgT2TftFP1iYtd5bX7vWJyM7u4jS8bEfW00+1C8RQA7OQ+0vPibmJ62C1QTRM5H1Kw+cHQ1NFnaOpvKv9IVVrHGDE3glr/ouq/RPtIUqEd4o+mUzZ/uX4Wbb9+XUy1+7HFjdkMcCLDsh2xIRjkDURUBBPwAh2V+RBXRI+X4H0AS6ImFbBJGLGcLgJlMNKyV8Zy6CSdUI9dZj1m6jcvLOrGerNMBO62oVEXpKUiGmQ/Z6PgoxZzh7pnpiiehCye7aym6EedUC/X4+RWfu5rP1osif1mSi5Kg8d5bmU+gD4xSdwCiGjACBOU6WHR7INGjkbDLM2KqmW7E2oUVfiTzWTAp8274m+J7HA0kgChb90JdaGpA4tB0=
  secret_access_key:
    secure: juB0NOgWp5KzBzqdlSt2byny6Muzbo1H3ZdJS/5q8PeLuJsb0WEEuNyf7/eH6wCgH4dkgkCigu/LMGN3qdAjYxr5gITTXut8upWo2gXstpX1yk6wTwSpbjQwStjJ5MK3kEEatCsk/LJZ/46S+gS6DphgZMXAeMr8udP6TijrBh9F822yUu9D6CejPmZPmPHm/yEIVGWGqWT6QWCrmUP2JTWwFEHiIzGWqZc+miZzdUZ6+PcpiPoDuC66h7ztKukOAmv6KWlKP2ExDPB/xgAw4RY1cJaJ1fAMVHFj1GqWkNYRFAQmVGhhCY6nWrSMcXv8gQKeDKF0DPJlZmSD/Te6ijpNJ7FcbzxVVpqKltQBBimxaOPEYVCosOxjHQhCQwSD0vqSfIi1oy7vDXg/X6Bzkmo/Hfahx5icEHNLOzRK1GXie+TW6eTAIFD+3TMl86x3JwdtkeCL5LUmXH08BjXGSbDd3UCERb7C11NGRLOnvgj6o+b5lmEB6PcchKyrhmnADF8mF9HS/n39xUFHX06wSjcM/60+m0VFsgatuAeLYUDdKTKggqSFfe650ivhVYHk8Kyz2Q5MxZlMxM96mqi0Coi/BCSLyCDHb2/47FcFPeplBvIp8m6X37Cj0jxchhcy8XMJ+OyFScCftLJaRTqcUtj+toNDgTDA1RaTe9pWFiM=
  bucket: librdkafka-ci-packages
  region: us-west-1
  local-dir: wheelhouse
  upload_dir: confluent-kafka-python/p-confluent-kafka-python__bld-travis__plat-${TRAVIS_OS_NAME}__tag-${TRAVIS_TAG}__sha-${TRAVIS_COMMIT}__bid-${TRAVIS_BUILD_ID}__
  acl: public_read
  cleanup: false
  on:
    repo: confluentinc/confluent-kafka-python
    all_branches: true
